name: Deploy to GitHub

on: [workflow_dispatch]
jobs:
  build:
    uses: ./.github/workflows/build.yml
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Download macOS ARM build
        uses: actions/download-artifact@v3
        with:
          name: build-macos-aarch64
          path: ./dist
          
      - name: Download macOS AMD64 build
        uses: actions/download-artifact@v3
        with:
          name: build-macos-amd64
          path: ./dist
        
      - name: Run Conveyor     
        uses: hydraulic-software/conveyor/actions/build@v10.1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            LOGGING: trace
        with:
          command: make copied-site          
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1
          
      - name: Dump Conveyor Log
        uses: hydraulic-software/conveyor/actions/build@v10.1
        with:
          command: "--show-log > ./conveyor-log.txt"
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1
          
      - name: 'Upload Conveyor Log'
        uses: actions/upload-artifact@v3
        with:
          name: conveyor-log.txt
          path: ./conveyor-log.txt
